# Generated by Django 2.0.3 on 2018-09-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='US_County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='US_State',
            fields=[
                ('short', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('full', models.CharField(max_length=100)),
                ('fips', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='us_county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='hda_privileged.US_State'),
        ),
    ]
