# Generated by Django 2.0.3 on 2018-09-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hda_privileged', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_set',
            name='source_document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
    ]
