# Generated by Django 2.0.3 on 2018-10-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hda_privileged', '0005_percentile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_point',
            old_name='percentile',
            new_name='rank',
        ),
    ]
