# Generated by Django 2.1.1 on 2018-11-17 15:22

import autoslug.fields
from django.db import migrations
import hda_privileged.models


class Migration(migrations.Migration):

    dependencies = [
        ('hda_privileged', '0007_auto_20181117_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_indicator',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=20, null=True, slugify=hda_privileged.models.Health_Indicator.custom_slugify, unique=True),
        ),
    ]
