image: python:3.6
pipeline:
  default:
    - step:
        name: Test
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install behave_django
          - python manage.py test